# Form implementation generated from reading ui file 'ITS_Device1.2.ui'
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class LoginWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(LoginWidget, self).__init__(parent)
        self.setObjectName("FILE-SET")
        self.resize(1314, 916)
        self.setAutoFillBackground(True)
        self.LoginWindow = QMainWindow()
        self.LoginWindow.setIconSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setMinimumSize(QtCore.QSize(15, 15))
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 76, 1251, 20))
        self.line.setAutoFillBackground(True)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line.setStyleSheet("background-color: #b8e7ff")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 291, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(480, 10, 331, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.comboBox.addItem("S-Cube")
        self.comboBox.addItem("GW")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(880, 10, 381, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Connect = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Connect.setFont(font)
        self.Connect.setObjectName("Connect")
        self.Connect.setStyleSheet("background-color: #15a5ff")
        self.horizontalLayout_3.addWidget(self.Connect)
        spacerItem = QtWidgets.QSpacerItem(98, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(630, 120, 20, 731))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_2.setStyleSheet("background-color: #d4d3d0")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 201, 51))#
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CurrentSetting = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.CurrentSetting.setFont(font)
        self.CurrentSetting.setObjectName("CurrentSetting")
        self.CurrentSetting.setStyleSheet("background-color: #89cff0")
        self.verticalLayout.addWidget(self.CurrentSetting)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(660, 100, 201, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ChangeSetting = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ChangeSetting.setFont(font)
        self.ChangeSetting.setObjectName("ChangeSetting")
        self.ChangeSetting.setStyleSheet("background-color: #89cff0")
        self.verticalLayout_2.addWidget(self.ChangeSetting)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 180, 241, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.AElineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AElineEdit.setFont(font)
        self.AElineEdit.setObjectName("AElineEdit")
        self.horizontalLayout_4.addWidget(self.AElineEdit)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(370, 180, 241, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.ITSlineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ITSlineEdit.setFont(font)
        self.ITSlineEdit.setObjectName("ITSlineEdit")
        self.horizontalLayout_5.addWidget(self.ITSlineEdit)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(660, 180, 241, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.AElineSettingEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AElineSettingEdit.setFont(font)
        self.AElineSettingEdit.setObjectName("AElineSettingEdit")
        self.horizontalLayout_6.addWidget(self.AElineSettingEdit)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(980, 180, 241, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.ITScomboBo = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ITScomboBo.setFont(font)
        self.ITScomboBo.setObjectName("ITScomboBo")
        self.horizontalLayout_7.addWidget(self.ITScomboBo)
        self.ITScomboBo.addItem("ITS1")
        self.ITScomboBo.addItem("ITS2")
        self.ITScomboBo.addItem("ITS3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 270, 121, 49))
        self.label_7.setObjectName("label_7")
        self.FileSaveDirTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.FileSaveDirTextEdit.setGeometry(QtCore.QRect(150, 280, 151, 31))
        self.FileSaveDirTextEdit.setObjectName("FileSaveDirTextEdit")
        self.FileSaveDirTextEdit.setFont(QtGui.QFont('Arial', 10))

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 270, 121, 49))
        self.label_8.setObjectName("label_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(410, 280, 151, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setFont(QtGui.QFont('Arial', 12))

        self.SamRateTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.SamRateTextEdit.setGeometry(QtCore.QRect(150, 320, 151, 31))
        self.SamRateTextEdit.setObjectName("SamRateTextEdit")
        self.SamRateTextEdit.setFont(QtGui.QFont('Arial', 12))

        self.FTtextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.FTtextEdit.setGeometry(QtCore.QRect(150, 360, 151, 31))
        self.FTtextEdit.setObjectName("FTtextEdit")
        self.FTtextEdit.setFont(QtGui.QFont('Arial', 12))
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(410, 320, 151, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_5.setFont(QtGui.QFont('Arial', 12))

        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(410, 360, 151, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_6.setFont(QtGui.QFont('Arial', 12))

        self.TPtextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.TPtextEdit.setGeometry(QtCore.QRect(150, 400, 151, 31))
        self.TPtextEdit.setObjectName("TPtextEdit")
        self.TPtextEdit.setFont(QtGui.QFont('Arial', 12))

        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(410, 400, 151, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_8.setFont(QtGui.QFont('Arial', 12))

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 310, 101, 49))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 350, 101, 49))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 390, 101, 49))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 480, 101, 49))
        self.label_12.setObjectName("label_12")
        self.FileServerIDtextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.FileServerIDtextEdit.setGeometry(QtCore.QRect(150, 490, 151, 31))
        self.FileServerIDtextEdit.setObjectName("FileServerIDtextEdit")
        self.FileServerIDtextEdit.setFont(QtGui.QFont('Arial', 12))

        self.FileServerPWTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.FileServerPWTextEdit.setGeometry(QtCore.QRect(450, 490, 151, 31))
        self.FileServerPWTextEdit.setObjectName("FileServerPWTextEdit")
        self.FileServerPWTextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(330, 480, 101, 49))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(660, 270, 121, 49))
        self.label_14.setObjectName("label_14")
        self.FileSaveDirtextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.FileSaveDirtextEdit.setGeometry(QtCore.QRect(780, 280, 151, 31))
        self.FileSaveDirtextEdit.setObjectName("FileSaveDirtextEdit")
        self.FileSaveDirtextEdit.setFont(QtGui.QFont('Arial', 10))

        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(980, 270, 121, 49))
        self.label_15.setObjectName("label_15")
        self.FileSaveDirkombo = QtWidgets.QComboBox(self.centralwidget)
        self.FileSaveDirkombo.setGeometry(QtCore.QRect(1120, 280, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.FileSaveDirkombo.setFont(font)
        self.FileSaveDirkombo.setObjectName("FileSaveDirkombo")
        self.FileSaveDirkombo.addItems(["BIN", "csv", "저장안함"])
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(660, 320, 121, 49))
        self.label_16.setObjectName("label_16")
        self.SampRatekombo = QtWidgets.QComboBox(self.centralwidget)
        self.SampRatekombo.setGeometry(QtCore.QRect(780, 330, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SampRatekombo.setFont(font)
        self.SampRatekombo.setObjectName("SampRatekombo")
        self.SampRatekombo.addItems(["1","5","10", "20", "50", "100", "150", "200"])
        self.FTkombo = QtWidgets.QComboBox(self.centralwidget)
        self.FTkombo.setGeometry(QtCore.QRect(780, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.FTkombo.setFont(font)
        self.FTkombo.setObjectName("FTkombo")
        self.FTkombo.addItem("1")
        self.FTkombo.addItem("5")
        self.FTkombo.addItem("10")
        self.FTkombo.addItem("20")
        self.FTkombo.addItem("30")
        self.FTkombo.addItem("60")
        self.FTkombo.addItem("300")
        self.FTkombo.addItem("600")
        self.TPkombo = QtWidgets.QComboBox(self.centralwidget)
        self.TPkombo.setGeometry(QtCore.QRect(780, 430, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TPkombo.setFont(font)
        self.TPkombo.setObjectName("TPkombo")
        self.TPkombo.addItems(["Periodic", "Event"])
        self.DAMkombo = QtWidgets.QComboBox(self.centralwidget)
        self.DAMkombo.setGeometry(QtCore.QRect(1120, 330, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.DAMkombo.setFont(font)
        self.DAMkombo.setObjectName("DAMkombo")
        self.DAMkombo.addItems(["MQTT", "ITS", "MQTT+ITS", "KT", "KT+MQTT", "KT+ITS"])
        self.S_Typekombo = QtWidgets.QComboBox(self.centralwidget)
        self.S_Typekombo.setGeometry(QtCore.QRect(1120, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.S_Typekombo.setFont(font)
        self.S_Typekombo.setObjectName("S_Typekombo")
        self.S_Typekombo.addItem("ACC-X")
        self.S_Typekombo.addItem("ACC-Y")
        self.S_Typekombo.addItem("ACC-Z")
        self.S_Typekombo.addItem("ACC-3A")
        self.S_Typekombo.addItem("Strain")
        self.S_Typekombo.addItem("DISP")
        self.S_Typekombo.addItem("LOAD")
        self.S_Typekombo.addItem("TILT")
        self.T_Syskombo = QtWidgets.QComboBox(self.centralwidget)
        self.T_Syskombo.setGeometry(QtCore.QRect(1120, 430, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.T_Syskombo.setFont(font)
        self.T_Syskombo.setObjectName("T_Syskombo")
        self.T_Syskombo.addItem("NTP")
        self.T_Syskombo.addItem("GPS")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(660, 370, 101, 49))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(660, 420, 101, 49))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(340, 310, 101, 49))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(340, 350, 101, 49))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(340, 390, 101, 49))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(980, 320, 101, 49))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(980, 370, 101, 49))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(980, 420, 101, 49))
        self.label_24.setObjectName("label_24")
        self.FileServerPWsettingsTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.FileServerPWsettingsTextEdit.setGeometry(QtCore.QRect(1090, 490, 151, 31))
        self.FileServerPWsettingsTextEdit.setObjectName("FileServerPWsettingsTextEdit")
        self.FileServerPWsettingsTextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(970, 480, 101, 49))
        self.label_25.setObjectName("label_25")
        self.FileSaveIDlsettingsTxtEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.FileSaveIDlsettingsTxtEdit.setGeometry(QtCore.QRect(790, 490, 151, 31))
        self.FileSaveIDlsettingsTxtEdit.setObjectName("FileSaveIDlsettingsTxtEdit")
        self.FileSaveIDlsettingsTxtEdit.setFont(QtGui.QFont('Arial', 12))


        self.FileSaveIDlabel = QtWidgets.QLabel(self.centralwidget)
        self.FileSaveIDlabel.setGeometry(QtCore.QRect(670, 480, 101, 49))
        self.FileSaveIDlabel.setObjectName("FileSaveIDlabel")
        self.sersorNumtextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.sersorNumtextEdit.setGeometry(QtCore.QRect(150, 540, 51, 31))
        self.sersorNumtextEdit.setObjectName("sersorNumtextEdit")
        self.sersorNumtextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(30, 530, 101, 49))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(670, 530, 101, 49))
        self.label_27.setObjectName("label_27")
        self.senNumSetgsTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.senNumSetgsTextEdit.setGeometry(QtCore.QRect(790, 540, 51, 31))
        self.senNumSetgsTextEdit.setObjectName("senNumSetgsTextEdit")
        self.senNumSetgsTextEdit.setFont(QtGui.QFont('Arial', 12))

        self.MacIPtextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.MacIPtextEdit.setGeometry(QtCore.QRect(150, 600, 441, 31))
        self.MacIPtextEdit.setObjectName("MacIPtextEdit")
        self.MacIPtextEdit.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter | QtCore.Qt.AlignCenter | QtCore.Qt.AlignHCenter )
        self.MacIPtextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(30, 590, 101, 49))
        self.label_28.setObjectName("label_28")
        self.SensitytextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.SensitytextEdit.setGeometry(QtCore.QRect(150, 650, 121, 31))
        self.SensitytextEdit.setObjectName("SensitytextEdit")
        self.SensitytextEdit.setFont(QtGui.QFont('Arial', 12))

        self.ExtFactortextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.ExtFactortextEdit.setGeometry(QtCore.QRect(150, 700, 121, 31))
        self.ExtFactortextEdit.setObjectName("ExtFactortextEdit")
        self.ExtFactortextEdit.setFont(QtGui.QFont('Arial', 12))

        self.RangetextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.RangetextEdit.setGeometry(QtCore.QRect(150, 750, 121, 31))
        self.RangetextEdit.setObjectName("RangetextEdit")
        self.RangetextEdit.setFont(QtGui.QFont('Arial', 12))

        self.GFactortextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.GFactortextEdit.setGeometry(QtCore.QRect(150, 790, 121, 31))
        self.GFactortextEdit.setObjectName("GFactortextEdit")
        self.GFactortextEdit.setFont(QtGui.QFont('Arial', 12))

        self.CaptextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.CaptextEdit.setGeometry(QtCore.QRect(470, 650, 121, 31))
        self.CaptextEdit.setObjectName("CaptextEdit")
        self.CaptextEdit.setFont(QtGui.QFont('Arial', 12))

        self.OffsettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.OffsettextEdit.setGeometry(QtCore.QRect(470, 700, 121, 31))
        self.OffsettextEdit.setObjectName("OffsettextEdit")
        self.OffsettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.VoltagetextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.VoltagetextEdit.setGeometry(QtCore.QRect(470, 790, 121, 31))
        self.VoltagetextEdit.setObjectName("VoltagetextEdit")
        self.VoltagetextEdit.setFont(QtGui.QFont('Arial', 12))

        self.exVolttextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.exVolttextEdit.setGeometry(QtCore.QRect(470, 750, 121, 31))
        self.exVolttextEdit.setObjectName("exVolttextEdit")
        self.exVolttextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(30, 640, 101, 49))
        self.label_29.setObjectName("label_29")
        self.pushButtonLeft = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLeft.setGeometry(QtCore.QRect(230, 540, 71, 31))
        self.pushButtonLeft.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rigtPoint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLeft.setIcon(icon)
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.pushButtonRight = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRight.setGeometry(QtCore.QRect(450, 540, 71, 31))
        self.pushButtonRight.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("leftPoint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRight.setIcon(icon1)
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(30, 690, 101, 49))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(30, 740, 101, 49))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(30, 780, 101, 49))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(340, 640, 101, 49))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(340, 690, 101, 49))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(340, 740, 101, 49))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(340, 780, 101, 49))
        self.label_36.setObjectName("label_36")
        self.CapChangSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.CapChangSettextEdit.setGeometry(QtCore.QRect(1040, 650, 121, 31))
        self.CapChangSettextEdit.setObjectName("CapChangSettextEdit")
        self.CapChangSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(670, 690, 101, 49))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(980, 740, 101, 49))
        self.label_38.setObjectName("label_38")
        self.SensityChangSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.SensityChangSettextEdit.setGeometry(QtCore.QRect(790, 650, 121, 31))
        self.SensityChangSettextEdit.setObjectName("SensityChangSettextEdit")
        self.SensityChangSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.VoltageChanSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.VoltageChanSettextEdit.setGeometry(QtCore.QRect(1040, 790, 121, 31))
        self.VoltageChanSettextEdit.setObjectName("VoltageChanSettextEdit")
        self.VoltageChanSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(670, 640, 101, 49))
        self.label_39.setObjectName("label_39")
        self.exVoltChanSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.exVoltChanSettextEdit.setGeometry(QtCore.QRect(1040, 750, 121, 31))
        self.exVoltChanSettextEdit.setObjectName("exVoltChanSettextEdit")
        self.exVoltChanSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(670, 590, 101, 49))
        self.label_40.setObjectName("label_40")
        self.RangeChangSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.RangeChangSettextEdit.setGeometry(QtCore.QRect(790, 750, 121, 31))
        self.RangeChangSettextEdit.setObjectName("RangeChangSettextEdit")
        self.RangeChangSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(980, 780, 101, 49))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(980, 640, 101, 49))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(980, 690, 101, 49))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(670, 780, 101, 49))
        self.label_44.setObjectName("label_44")
        self.GFactorChanSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.GFactorChanSettextEdit.setGeometry(QtCore.QRect(790, 790, 121, 31))
        self.GFactorChanSettextEdit.setObjectName("GFactorChanSettextEdit")
        self.GFactorChanSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.MacIPChanSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.MacIPChanSettextEdit.setGeometry(QtCore.QRect(790, 600, 371, 31))
        self.MacIPChanSettextEdit.setObjectName("MacIPChanSettextEdit")
        self.MacIPChanSettextEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MacIPChanSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(670, 740, 101, 49))
        self.label_45.setObjectName("label_45")
        self.ExtFactorChangSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.ExtFactorChangSettextEdit.setGeometry(QtCore.QRect(790, 700, 121, 31))
        self.ExtFactorChangSettextEdit.setObjectName("ExtFactorChangSettextEdit")
        self.ExtFactorChangSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.OffsetChanSettextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.OffsetChanSettextEdit.setGeometry(QtCore.QRect(1040, 700, 121, 31))
        self.OffsetChanSettextEdit.setObjectName("OffsetChanSettextEdit")
        self.OffsetChanSettextEdit.setFont(QtGui.QFont('Arial', 12))

        self.pushButtonSetLeft = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSetLeft.setGeometry(QtCore.QRect(860, 540, 71, 31))
        self.pushButtonSetLeft.setText("")
        self.pushButtonSetLeft.setIcon(icon)
        self.pushButtonSetLeft.setObjectName("pushButtonSetLeft")
        self.pushButtonSetRight = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSetRight.setGeometry(QtCore.QRect(1090, 540, 71, 31))
        self.pushButtonSetRight.setText("")
        self.pushButtonSetRight.setIcon(icon1)
        self.pushButtonSetRight.setObjectName("pushButtonSetRight")
        self.ApplyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ApplyBtn.setGeometry(QtCore.QRect(1180, 650, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ApplyBtn.setFont(font)
        self.ApplyBtn.setObjectName("ApplyBtn")
        self.ApplyBtn.setStyleSheet("background-color:#debc97;")
        self.DeleteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteBtn.setGeometry(QtCore.QRect(710, 830, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.DeleteBtn.setFont(font)
        self.DeleteBtn.setObjectName("DeleteBtn")
        self.DeleteBtn.setStyleSheet("background-color:#80f5ff;")
        self.AddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AddBtn.setGeometry(QtCore.QRect(970, 830, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AddBtn.setFont(font)
        self.AddBtn.setObjectName("AddBtn")
        self.AddBtn.setStyleSheet("background-color:#80f5ff;")
        self.textEditCurSet = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditCurSet.setGeometry(QtCore.QRect(340, 540, 61, 31))
        self.textEditCurSet.setObjectName("textEditCurSet")
        self.textEditCurSet.setFont(QtGui.QFont('Arial', 12))

        self.textEditSetChan = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSetChan.setGeometry(QtCore.QRect(980, 540, 61, 31))
        self.textEditSetChan.setObjectName("textEditSetChan")
        self.textEditSetChan.setFont(QtGui.QFont('Arial', 12))

        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1314, 21))
        self.menubar.setObjectName("menubar")
        self.LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.LoginWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(self.LoginWindow)
